adapter:
  image: node:16
  volumes:
    - $PWD:/home/node/sails-mongo
  links:
    - mongo
  environment:
    - WATERLINE_ADAPTER_TESTS_DATABASE=sails-mongo
    - WATERLINE_ADAPTER_TESTS_URL=mongo/testdb
    - WATERLINE_ADAPTER_TESTS_HOST=mongo
    - NODE_ENV=test
  user: node
  working_dir: /home/node/sails-mongo
  command:
    - bash -c "npm test"

mongo:
  image: mongo:6.0
  restart: always
  command: "--logpath=/dev/null"
  ports:
    - "27017:27017"
